### ISSUE TITLE
How can I get OpenCL.framework Headers

### ISSUE THREAD

**Issue by xuezu29** [MP0w/iOS-Headers#2]
First,thank you for sharing! But I can't find OpenCL.framework Headers ,and how can get it? Thanks very mach.(ps:I am Chinese ,and my English is not very well.Hope you could understand me.)

**Comment by MP0w** [comment]
Probably there is not to class dump in that framework https://github.com/MP0w/iOS-Headers/tree/master/iOS7/PrivateFrameworks/OpenCL

**Comment by xuezu29** [comment]
So thanks for your reply!  I have read that file, actually it is an empty head file. Before I used class-dump to extract header files also is such.

**Comment by MP0w** [comment]
There is no Objective C in OpenCL, so nothing to class-dump
